### PR TITLE
Typo issue

### PR DESCRIPTION
**Pull request by llewan**

### CODE REVIEW

**Comment by ghengeveld** [comment]
Thanks for the bugfix. I don't think `.idea` should be in a project specific gitignore. Instead you should create a global gitignore in your home directory containing all sorts of things you never want to add to git, such as editor specific files and OS files. There's plenty of examples available online.

**Comment by raboof** [comment]
Github maintains a set of useful templates for your global gitignore at https://github.com/github/gitignore

**Comment by llewan** [comment]
Thanks guys for the suggestion it sounds pretty good.
So, removed the .idea commit and I think this PR is ready to merge

**Comment by ghengeveld** [comment]
Unfortunately I don't have write access to this repository anymore because I'm no longer with Wehkamp. @raboof do you still have access?

**Pull request merged**
