### PR TITLE
Ensure a forward slash in baseUrl

### PR DESCRIPTION
**Pull request by nicolaevladescu**
Ensure a forward slash in baseUrl if the user ommits it or does not think it's mandatory (and it should not be imho)

### CODE REVIEW

**Comment by ghengeveld** [comment]
Hi Nicolae,

Do you use this library in a serious project? I no longer use it, nor does Wehkamp, and I don't have write access to this repo anymore, so I'm looking for someone to fork this project and become the primary maintainer. Would you be interested? I can give you npm publish access.

**Comment by nicolaevladescu** [comment]
Hello.

No i'm not using it in a production or serious project, also my main focus isn't JavaScript.
I can use my own fork for my endeavors, i just wanted to push it upstream maybe some other people may find my additions useful.

Although i can spare some little time to maintain, not developing JavaScript on a daily basis and not being up to speed with the JavaScript, NodeJS community  and ES specs will leave me out of date with many improvements and/or new features, so in that aspect i don't think i could be a good primary maintainer.

Thank you for the reply, i can close this if you cannot accept it.

**Comment by ghengeveld** [comment]
Thanks for the honest answer. I have forked the repo to my own account so at least I can maintain it. Could you file this pull request against https://github.com/ghengeveld/atlassian-crowd-client? I can accept it there.

**Comment by nicolaevladescu** [comment]
Sure, no problem, thank you also!

**Pull request closed without merging**
